### ISSUE TITLE
Not work on Lollipop - LG G3 D855

### ISSUE THREAD

**Issue by rfazi** [apsun/NoUsbNotification#1]
This module not work on LG G3 D855 with Lollipop 5.0. Version: V21a.

**Comment by apsun** [comment]
I'm going to need more info than that. Can you post your logcat output?

`adb logcat -s "NoUsbNotification"` (make sure you're running v1.0.1)

Also please post the contents of your Xposed log (find that in the Xposed Installer app)

**Comment by rfazi** [comment]
**Xposed log:**
[xposed_error_20160214_005034.txt](https://github.com/apsun/NoUsbNotification/files/129458/xposed_error_20160214_005034.txt)

There are no logcat for "NoUsbNotification".

**Comment by apsun** [comment]
Hmm, there doesn't seem to be any errors. Can you restart your phone, connect/disconnect your phone to your computer one or two times, and post your logcat again? Thanks.

Also, what do you mean by 'not work'? Do you still get the USB/ADB notification? Which app is it coming from? (Long press the notification, and it should show the source app)

**Comment by rfazi** [comment]
Yes the notification appear from Android system.

The logcat is empty.

Can you upload an alpha version to xposed with many logs so i can download it and post them here?

**Comment by apsun** [comment]
Okay, can you install these two files please?

https://a.uguu.se/jtbygi_NoUsbNotification-release.apk
https://a.uguu.se/axofgk_DebugKit-release.apk

(Make sure to enable the DebugKit app in Xposed)

Then reboot your phone and post the contents of your Xposed log (no logcat needed this time). Also, long press the USB notification, and press the (i) icon on the right, it should pop up with a stacktrace, post a screenshot of that too (you may have to rotate your device into landscape to see the whole output)

**Comment by rfazi** [comment]
Xposed log:
[xposed_error_20160214_174157.log.txt](https://github.com/apsun/NoUsbNotification/files/129784/xposed_error_20160214_174157.log.txt)

In the log at the end i take the screenshot of the notification because when i long press on the notification no (i) icon on the right appear for read the stacktrace.
![screenshot_2016-02-14-17-41-35](https://cloud.githubusercontent.com/assets/9641390/13034951/27e74698-d343-11e5-8f44-7f0ed0b3a971.png)

**Comment by apsun** [comment]
Oh my bad, the (i) thing was added in Android 6.0.

I found the problem, your ROM has modified some of the system methods. Try this build: https://a.uguu.se/szdksa_NoUsbNotification-release.apk

**Comment by rfazi** [comment]
Now work! Thanks
