### ISSUE TITLE
Sony XPeria Z1 Compact

### ISSUE THREAD

**Issue by Fabian42** [apsun/NoUsbNotification#3]
This mod completely messes up my Sony XPeria Z1 Compact. Whenever this mod is active,...
- SwiftKey keyboard, Music visualisation wallpaper, Google Play services and more get forced closed every few seconds
- Google sheets and Google Drive open randomly
- messages of the messaging app Telegram reappear over and over
- when I try to activate WiFi, the activation animation loops without actually doing anything
- XPosed tells me (in the tab "Framework") that it isn't compatible with my Android version or processor, but all mods still work. The "install" button is greyed out.
- deactivating mods isn't possible, after a restart they are still active
- I was able to fix it temporarily by activating and deactivating stamina mode multiple times, but after a restart it was there again.
  Very weird. And I have no idea what all of this has to do with an USB notification, but it happens whenever the mod is active.
  I have Android 4.3 (the preinstalled OS on my phone) and my other mods are:
  3C Toolbox Pro, AccountSectionRemove, ActivityForceNewTask, AdBlocker, All Notifications Expanded, Bluetooth ToolKit, Cool Tool Pro (inactive), Copy Toast, CrappaLinks, Disable Charging LED, Disable Fullscreen Keyboard, GravityBox, Hide Notification Panel Handle, Hodor (inactive), MinMinGuard, Notification Count, PinNotif, Play Store Changelog, Play Store link in App info, PlayPermissionsExposed, SB Icon Hider, Settings Patcher for Xperia, Statusbar download progress, TimePicker Fix, UnbelovedHosts, Xperia QuickSettings LongClick, Xperia S Tweaks for JellyBean 4.1.2, Xperia™ Xposed, Xposed Additions, Xposed Macro Expand, XuiMod, YouTube AdAway, YourTube (may change to OG YouTube soon)
  Date of this data: 16.2.2016

**Comment by apsun** [comment]
That's weird. Can you try disabling your other notification-related modules and reinstalling NoUsbNotification? All this app does is force the methods responsible for showing the ADB/USB notifications to abort early. Also, if you could post your logcat output + Xposed log that would be great.

**Comment by Fabian42** [comment]
Reinstalling it apparently worked.

Fabian Röling
Phone: Sony XPeria Z1 Compact
Mods: 3C Toolbox Pro, AccountSectionRemove, ActivityForceNewTask,
AdBlocker, All Notifications Expanded, Bluetooth ToolKit, Cool Tool Pro
(inactive), Copy Toast, CrappaLinks, Disable Charging LED, Disable
Fullscreen Keyboard, GravityBox, Hide Notification Panel Handle, Hodor
(inactive), MinMinGuard, Notification Count, PinNotif, Play Store
Changelog, Play Store link in App info, PlayPermissionsExposed, SB Icon
Hider, Settings Patcher for Xperia, Statusbar download progress, TimePicker
Fix, UnbelovedHosts, Xperia QuickSettings LongClick, Xperia S Tweaks for
JellyBean 4.1.2, Xperia™ Xposed, Xposed Additions, Xposed Macro Expand,
XuiMod, YouTube AdAway, YourTube (may change to OG YouTube soon)
Laptop+PC: Windows 7 64 bit
Date of this data: 16.2.2016
Am 29.02.2016 14:22 schrieb "Andrew Sun" notifications@github.com:

**Comment by Fabian42** [comment]
After some reboots all the bugs were there again. I don't know if XPosed
was active or inactive or something in between, it gave me all kinds of
error messages.
Apparently my phone managed to partially unroot itself (if that's even
possible). Running Towelroot again seems to have fixed it (for now?).

Fabian Röling
Phone: Sony XPeria Z1 Compact
Mods: 3C Toolbox Pro, AccountSectionRemove, ActivityForceNewTask,
AdBlocker, All Notifications Expanded, Bluetooth ToolKit, Cool Tool Pro
(inactive), Copy Toast, CrappaLinks, Disable Charging LED, Disable
Fullscreen Keyboard, GravityBox, Hide Notification Panel Handle, Hodor
(inactive), MinMinGuard, Notification Count, PinNotif, Play Store
Changelog, Play Store link in App info, PlayPermissionsExposed, SB Icon
Hider, Settings Patcher for Xperia, Statusbar download progress, TimePicker
Fix, UnbelovedHosts, Xperia QuickSettings LongClick, Xperia S Tweaks for
JellyBean 4.1.2, Xperia™ Xposed, Xposed Additions, Xposed Macro Expand,
XuiMod, YouTube AdAway, YourTube (may change to OG YouTube soon)
Laptop+PC: Windows 7 64 bit
Date of this data: 16.2.2016
Am 29.02.2016 18:35 schrieb "FaRo" fabianroeling@googlemail.com:

**Comment by apsun** [comment]
If you are sure that the problem does not occur when NoUsbNotification is not installed, then it is likely a conflict with another mod you have installed, or a serious problem with your ROM. Please post your Xposed logs so I can take a look at what's going on.

**Comment by Fabian42** [comment]
It also happened while your mod was uninstalled and all other mods probably
inactive, as well as most other apps, so it doesn't seem to have something
to do with your mod, unlike I previously thought. But here is my log anyway.

Fabian Röling
Phone: Sony XPeria Z1 Compact
Mods: 3C Toolbox Pro, AccountSectionRemove, ActivityForceNewTask,
AdBlocker, All Notifications Expanded, Bluetooth ToolKit, Cool Tool Pro
(inactive), Copy Toast, CrappaLinks, Disable Charging LED, Disable
Fullscreen Keyboard, GravityBox, Hide Notification Panel Handle, Hodor
(inactive), MinMinGuard, Notification Count, PinNotif, Play Store
Changelog, Play Store link in App info, PlayPermissionsExposed, SB Icon
Hider, Settings Patcher for Xperia, Statusbar download progress, TimePicker
Fix, UnbelovedHosts, Xperia QuickSettings LongClick, Xperia S Tweaks for
JellyBean 4.1.2, Xperia™ Xposed, Xposed Additions, Xposed Macro Expand,
XuiMod, YouTube AdAway, YourTube (may change to OG YouTube soon)
Laptop+PC: Windows 7 64 bit
Date of this data: 16.2.2016
Am 01.03.2016 00:23 schrieb "Andrew Sun" notifications@github.com:

**Comment by apsun** [comment]
It seems you forgot to attach your log. Anyways, if the issue occurs without NoUsbNotification installed, I don't think I can help much, sorry.
